version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2
  slack: circleci/slack@4.1

workflows:
  sample:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          requires:
            - node/test # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: master # Uncomment this line
          post-steps:
            - slack/notify:
                event: pass
                template: success_tagged_deploy_1
            - slack/notify:
                event: fail
                template: basic_fail_1
                # custom: |
                #   {
                #     "blocks": [
                #       {
                #         "type": "section",
                #         "fields": [
                #           {
                #             "type": "plain_text",
                #             "text": "*This is a fail notification*",
                #             "emoji": true
                #           }
                #         ]
                #       }
                #     ]
                #   }
